version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/your_db_name?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - db
  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    environment:
      SERVER_NAME: api  # Here we set the environment variable 'SERVER_NAME' to 'api'
    depends_on:
      - api

volumes:
  db_data: {}
